### ISSUE TITLE
ISSUES

### ISSUE THREAD

**Issue by IshtpreetCheema** [haomateach/info1112#14]
100410466 I am facing these two problems while coding when i run favorite number code pls tell me. I am not getting it right.
E:/workspaceone/workspaceone/workspaceone/main.cpp:7:5: error: expected initializer before 'std'
E:/workspaceone/workspaceone/workspaceone/main.cpp:8:18: error: 'favorite_number' was not declared in this scope

**Comment by needtostayawake** [comment]
100421379 well it looks like you forgot to initialize your variable aka you didn't assign it a value ( you can assign value as a constant or you can assign a value at run time). that's why it says your favorite_number isn't declared, to declare a variable you need to have a 1)variable type and a 2)variable name and then you need to initialize it by giving it a value. example below:

int age {21};   <----- here int is the variable type, age is the variable name, and 21 is the assigned value.

since you're asking the user for the favorite_number, write the source code like this:
int favorite_number;
std::cin >> favorite_number;
