### ISSUE TITLE
Regarding Quiz 2

### ISSUE THREAD

**Issue by NimzM** [haomateach/info1112#25]
Student ID: 100410376
Regarding Quiz 2 - Question 2:

I didn't understand why the output was choice "d" and not choice "a":
**Code:** 
    int x = 5;

    if (x = 2)
        cout << "This is true!" << endl;
    else
        cout << "This is false!" << endl;
        cout << "That's all, folks!" << endl;

**Output:**

d. This is true!
    That's all, folks!

**Comment by haomateach** [comment]
Key point 1:
Notice it's x=2, not x==2 after the if statement. Value of the expression x = 2 is actually 2, which is non-zero, which will be interpreted as TRUE. 

If it's x ==2, then the value of the expression x==2 will be FALSE, since x was assigned to be 5. 

Key point 2:
else can only take on the next statement, since { } is not used.

**Comment by NimzM** [comment]
Understood. Thanks a lot professor.
