### ISSUE TITLE
Assignment 4 Submission

### ISSUE THREAD

**Issue by Ravjot19** [haomateach/info1112#48]
ID- 100379866.

I still am a bit unclear with the submission, is it mandatory to submit header files? or can we submit just the .cpp file like we have been for the past assignments.

**Comment by Zuptex** [comment]
I don't think the program will run without the header files. Try opening main.cop outside of your workspace. It won't work because the classes are declared in you header files. 

int main()
{
First object1;
Second object2;
cout << object1.getVal() << endl;
cout << object2.getVal() << endl;
return 0;
}

The program won’t run because it’s missing the classes “First” and “Second”.

**Comment by mannugaddhyan** [comment]
i can help you mate. Send me a mail at:- 
blood.good2840@gmail.com

**Comment by mannugaddhyan** [comment]
i can help. Mail me at:
blood.good2840@gmail.com

**Comment by haomateach** [comment]
@Ravjot19 If you follow the standard way of class definition, you should have a few header files.
